#!/usr/bin/env python3
"""Generate portable skill references from the maintained mdoc manuals."""
import argparse
import os
from pathlib import Path
import re
import subprocess

ROOT = Path(__file__).resolve().parent.parent
SKILL = ROOT / "skills/served"
PAGES = {"served.1": "cli.md", "served.5": "config.md"}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for page, reference in PAGES.items():
        source = ROOT / "docs/man" / page
        subprocess.run(["mandoc", "-T", "lint", "-W", "warning", str(source)], check=True)
        output = subprocess.run(
            ["mandoc", "-T", "markdown", str(source)], check=True,
            capture_output=True, text=True, env={**os.environ, "LC_ALL": "C"},
        ).stdout
        # Preserve Markdown hard breaks without trailing whitespace.
        output = re.sub(r" {2,}\n", lambda _: chr(92) + "\n", output)
        for section, target in [(1, "cli.md"), (5, "config.md")]:
            output = output.replace(f"served({section})", f"[served({section})]({target})")
        output = "<!-- Generated by make docs; edit docs/man instead. -->\n\n" + output
        destination = SKILL / "references" / reference
        if args.check:
            if not destination.is_file() or destination.read_text() != output:
                raise SystemExit(f"stale reference: {destination}; run make docs")
        else:
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_text(output)
    # This skill deliberately uses only two single-line YAML scalar fields.
    source = (SKILL / "SKILL.md").read_text()
    if not re.match(r"\A---\nname: served\ndescription: [^\n]+\n---\n", source):
        raise SystemExit("SKILL.md requires name and a single-line description")
    for path in SKILL.rglob("*.md"):
        text = path.read_text()
        if "[TODO:" in text:
            raise SystemExit(f"unfinished scaffold: {path}")
        for link in re.findall(r"\]\(([^)]+)\)", text):
            if "://" in link or link.startswith("#"):
                continue
            target = (path.parent / link.split("#", 1)[0]).resolve()
            if not target.is_relative_to(SKILL) or not target.is_file():
                raise SystemExit(f"missing or nonportable skill reference: {path}: {link}")
    print("manuals and skill references are valid")


if __name__ == "__main__":
    main()
